### PR TITLE
feat: implemented a reset feature when a user has selected a province

### LINKED ISSUE #25: ✏️ Enhancement: Add a way to reset selected provinces
After testing the map, and selected more than 10 provinces, I realized that there's no way to reset the map to the default state. 

https://www.my-philippines-travel-level.com/map?levels=00050000000350000000301000000000000000000005000300000000414005300000000000000000000

Maybe add a reset button

### PR DESCRIPTION
**Pull request by chaaals**
Closes #25 

## Description
This PR adds a reset feature to the web app.

## Implementation Details
I utilized context api in this change so that we can make `provinceLevels` a global state. I implemented the `reset button` beside the `save image` button. I also implemented a constraint that users will only be able to reset when at least 1 province is selected. I also added a toast for better UX :))

## Demo
https://user-images.githubusercontent.com/70326902/234785985-728af0c3-1f8b-4c2f-902b-964088be052d.mp4

### CODE REVIEW

**Comment by jofftiquez** [comment]
Nice, this is exactly what I was looking for. Thank you!

**Review by jofftiquez — APPROVED** [review]
Looks good to me, but I'll let a react expert do another review. Thanks.

**Comment by jofftiquez** [comment]
@denzdelvillar @warengonzaga do you mind reviewing this? Thanks.

**Comment by jofftiquez** [comment]
> LGTM, good to have a custom message after reset.

I'm good with the current message in the success snackbar. Do you have something else in mind?

**Comment by warengonzaga** [comment]
> > LGTM, good to have a custom message after reset.
> 
> I'm good with the current message in the success snackbar. Do you have something else in mind?

No, I mean glad to have the message after reset.

**Review by denzdelvillar — COMMENTED** [review]
Looks good to me, thanks for this

**Pull request merged**
