### PR TITLE
Fix black box appearing when tapping on islands with WebKit-based mobile browsers

### LINKED ISSUE #24: Visual artefacts on mobile related to hover behavior
Hover behavior works well on desktop: Province name shows up and Province area becomes highlighted as gray. However on mobile, there is some visual artefact that seems to be related to the highlighting behavior for mouse hover. Refer to the video below:

https://user-images.githubusercontent.com/87693272/234027860-68a39288-53cd-4650-ab96-7bc222e58364.MOV

Clicking Albay at 00:06 produces a hover behavior to Northern Samar. Likewise, clicking Bukidnon at 00:11 produced the same behavior to Maguindanao del Sur.

### PR DESCRIPTION
**Pull request by mackyclemen**
This pull request fixes #24 in iOS browsers running the WebKit-based renderer. 

WebKit seems to add a highlight on elements that have a 'tap' event similar to the behavior in #24 - this behavior can be controlled using the [`-webkit-tap-highlight-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color) property on the element's style.

I've set the color of the said property to `transparent` to hide the box when an island is tapped, but feel free to modify as required.

Tested on iPhone 8, iOS 16.4.1, Safari.

---
## Before and After this PR

https://user-images.githubusercontent.com/17867386/235353619-8f3e4ad6-c44e-492b-b27e-07d34b7ee4db.mp4 

https://user-images.githubusercontent.com/17867386/235353631-9b1b75cc-0a85-4d08-b5ef-8ec9c731c75b.mp4

### CODE REVIEW

**Review by jofftiquez — APPROVED** [review]

**Comment by jofftiquez** [comment]
Hello @mackyclemen thanks for this. Could you provide a screenshot comparison of the broken vs fixed result? Thanks

**Comment by mackyclemen** [comment]
> Hello @mackyclemen thanks for this. Could you provide a screenshot comparison of the broken vs fixed result? Thanks

Sure thing. I'll record a before-and-after comparison in a while after I get home.

**Review by warengonzaga — APPROVED** [review]
LGTM 🙌

**Comment by mackyclemen** [comment]
Hello @jofftiquez, I've added the comparison videos on the PR infobox. The videos are recorded after the main branch has been merged, but I believe this shouldn't have any differences from what this PR is fixing. Let me know what you think!

**Review by jofftiquez — APPROVED** [review]

**Comment by jofftiquez** [comment]
> Hello @jofftiquez, I've added the comparison videos on the PR infobox. The videos are recorded after the main branch _have_ been merged, but I believe this shouldn't have any differences from what this PR is fixing. Let me know what you think!
> 
> EDIT: tense

Ok with me thanks

**Comment by warengonzaga** [comment]
All good to me too, thank you for the fix @mackyclemen, @denzdelvillar the final review is yours.

**Comment by jofftiquez** [comment]
@denzdelvillar I nominate this for merging, thanks

**Comment by denzdelvillar** [comment]
Looks good to me. Will merge. Thanks for this!

**Review by denzdelvillar — APPROVED** [review]

**Pull request merged**
